### ISSUE TITLE
Text block type can get other blocks' data stored with it

### ISSUE THREAD

**Issue by patrickmj** [omeka/plugin-ExhibitBuilder#105]
To reproduce, create a new exhibit and new page for it. Add a block of type text, and a block of type file-text. Save, then reorder. In the database, the text block will have the options for the file-text block stored on it.

Doesn't seem to cause any problems in practice, but something that seemed odd in the database.

**Comment by zerocrates** [comment]
I'm not able to reproduce this, at least not immediately.

**Comment by zerocrates** [comment]
Yeah, I tried on an existing exhibit but a new page with the blocks as described, and then on a new exhibit, totally following the instructions: not seeing the problem.

Reordering the two blocks just alters the order values for each. The options for the text block remain as NULL.

**Comment by patrickmj** [comment]
Tried some variations, and I'm still getting it, with tons of plugins deactivated. Maybe it's on an additional save, without changing anything?
