### ISSUE TITLE
Possible API issue

### ISSUE THREAD

**Issue by patrickmj** [omeka/plugin-ExhibitBuilder#106]
On `/api/exhibits` on two sites, I've seen the JSON being reported as not well-formed:

```
There was an error parsing the JSON document. The document may not be well-formed.
expected ',' or '}' after property value in object at line 1 column 6196 
```
Not sure how consistent this is, or where it might be coming from. Anyone able to reproduce this?

The API data from most of the individual exhibits doesn't show problems, but I have lots more to try to go through.

**Comment by zerocrates** [comment]
Got a linkable example of a problem site?

The API stuff should be getting generated with json_encode and/or Zend's JSON encoder so it shouldn't be possible to generate invalid output.

**Comment by patrickmj** [comment]
Via https://forum.omeka.org/t/api-import-fails-to-bring-exhibits/2798

https://library.lehigh.edu/omeka/api/exhibits

Their issue doesn't seem related to this, just something I `Notice`d 

#seeWhatIDidThere

**Comment by patrickmj** [comment]
That's the message that Firefox's JSON parser plugin gives me, btw.

**Comment by zerocrates** [comment]
Nothing I've thrown at it complains about anything with that JSON, so I'm inclined to point the finger at whatever's producing that message (I don't see anything from just looking at the page in Firefox, is it an extension perhaps?)

**Comment by zerocrates** [comment]
Ah I just now see the "plugin" part of your last message.

**Comment by patrickmj** [comment]
Yes. JSONView addon https://jsonview.com/

**Comment by zerocrates** [comment]
Possibly/likely this https://github.com/bhollis/jsonview/issues/143

**Comment by patrickmj** [comment]
Indeed. That looks like it. So, more than likely.
