### ISSUE TITLE
Exhibit Builder is stripped html

### ISSUE THREAD

**Issue by jcmundy** [omeka/plugin-ExhibitBuilder#111]
Exhibit builder is stripping html that is allowed in Simple pages.  Is there somewhere I can edit allowed elements (without turning off html filtering completely)?  Exhibit builder 3.3.1; Omeka 2.4.1

**Comment by zerocrates** [comment]
Have you already tried the Allowed Elements list in Settings -> Security? Exhibit Builder doesn't really have anything special of its own for HTML filtering.

**Comment by jcmundy** [comment]
Yes, I have put the elements in Settings -> Security in various orders, but it is still stripping.

**Comment by zerocrates** [comment]
What kind of elements are these that are being stripped?

The wildcard that sometimes causes problems is TinyMCE, which occasionally likes to remove elements on its own even when we try to prevent that.

Also, you mentioned turning off the filtering entirely... if you do that temporarily, does that fix the problem? If so, that would conclusively mean it's the regular core HTML filtering that's causing your problem, not anything else odd.

**Comment by jcmundy** [comment]
I want to add the name or id element to a link <a href>.  It will only all the title element.

**Comment by jcmundy** [comment]
If I turn of html filtering it doesn't strip the code.

**Comment by zerocrates** [comment]
Can you share what you've tried in the security settings page? The specific things you're talking about aren't elements, they're attributes, so you have to put them in the proper place when you're trying to allow them.

**Comment by jcmundy** [comment]
I tried adding a.name and a.id to the Allowed HTML Attributes

**Comment by zerocrates** [comment]
You can't allow the "id" attribute unless you're using Omeka 2.5 or newer. As for "name," I'm not as sure... it seems to work fine on 2.5 as well, but I'm not totally certain of what the prior behavior with that attribute is.

This is working on Simple Pages likely only because you have the Simple Pages option to actually filter HTML unchecked.

**Comment by jcmundy** [comment]
Thank you for your help.
