### ISSUE TITLE
Test tinymce4

### ISSUE THREAD

**Issue by zerocrates** [omeka/plugin-ExhibitBuilder#117]
(see omeka/omeka#837)

branch "tinymce4", requires core branch "tinymce4"

Editors appear in HTML-containing blocks, as well as Caption editors for attachments.

Of particular special interest here is that things work correctly when blocks are dragged around, added, removed.

**Comment by mebrett** [comment]
Moving blocks, adding, deleting blocks does not alter formatting or embeds. iFrames and other embeds work fine.

**Comment by mebrett** [comment]
I'm having an odd issue in Firefox where after moving blocks only the wysiwyg bar shows up in the block *until* I save changes, and then the text reappears. @alyssafahringer can you replicate it? (Want to be sure it's not just my version of firefox)

![screen shot 2018-02-07 at 4 37 08 pm](https://user-images.githubusercontent.com/2314070/35942887-4e18aad8-0c25-11e8-95be-853a7682add2.png)

**Comment by mebrett** [comment]
Resolved by John just now.
