### ISSUE TITLE
Exhibit show.php does not update

### ISSUE THREAD

**Issue by jcmundy** [omeka/plugin-ExhibitBuilder#123]
I am working with a plugin to add some translation elements to an Omeka site.  When I edit the Exhibit summary.php it updates as expected, but nothing I do to the Exhibit show.php page updates on the live site.  Is there a different file that Omeka is reading for the exhibits/show/exhibit-title/exhibit-page-title page?

Thank you!

**Comment by zerocrates** [comment]
Maybe your current theme has a custom exhibits/show.php file?

**Comment by jcmundy** [comment]
Thank you!  That is probably it!
