### ISSUE TITLE
Advanced search not correctly themeable

### ISSUE THREAD

**Issue by DBinaghi** [omeka/plugin-ExhibitBuilder#127]
Hello.
Just noticed that the html for the advanced search (`exhibit-builder-advanced-search.php`) doesn't seem to match the code already present in the general `search-form.php`: in this last, number of columns does not seem to be involved. 
I suggest to remove "two columns" and "five columns" from the div classes.
Hope this helps,
Daniele

**Comment by zerocrates** [comment]
So (many months later): you're talking here about the public view, right?

I think the root of this issue is that the plugin is using a single view for both admin and public. The admin core search form does have those columns classes.

**Comment by zerocrates** [comment]
This should be resolved by 4e95fa319be55bf431ed229b6e7cb5e6c48901be
