### ISSUE TITLE
Individual block expand/collapse buttons nonfunctional

### ISSUE THREAD

**Issue by zerocrates** [omeka/plugin-ExhibitBuilder#135]
https://forum.omeka.org/t/exhibitbuilder-expand-collapse-issue/15044

I imagine this is a regression from the new 3.0 admin theme.

**Comment by zerocrates** [comment]
@kimisgold looks like this was caused by 8d04af635cd58b85e4b2c9937f009fed2813e1b0: you reworked the options sections to work on a class but the same expander/collapser is used for the whole block as well.

**Comment by kimisgold** [comment]
This should now be addressed in https://github.com/omeka/plugin-ExhibitBuilder/commit/192a122adb86ddc351b280616782320b7566f162.

**Comment by zerocrates** [comment]
Fix finalized in 841bd93781e6e1c6ee31d5e8db576dbac8e155d0
