### ISSUE TITLE
ExhibitBuilder Carousel Block Testing

### ISSUE THREAD

**Issue by matthewjmckinley** [omeka/plugin-ExhibitBuilder#137]
On the new ExhibitBuilder Carousel block found on this branch https://github.com/omeka/plugin-ExhibitBuilder/tree/block-layout-carousel, please test:

- adding/removing/re-ordering images of different size and shape
- adding titles and captions of various lengths
- with a test set of various size images/captions, adjusting various settings and configurations
- all of the above in various themes and browsers

**Comment by katknow** [comment]
This is working really well for me across browsers and over multiple themes. The only weirdness is with padding of overlay captions, but since you mention that you may need to adjust the CSS I'm guessing that is okay. For some reason I cannot edit titles in my Omeka instance right now so I can't try a super ridiculously long item title, but the ones of different reasonable lengths seem to be working fine.

**Comment by matthewjmckinley** [comment]
Thanks for testing--yes, the styling of the overlaid title/caption is I think basic by design, so that users can customize to their liking.

**Comment by matthewjmckinley** [comment]
Hi Katie, Kim has implemented some changes to make the "Stretch Image to Fill" option look nicer and function better. Could you test that option specifically with some different sized images and file size settings and confirm that:

- 'Fill Width' stretches to the width of the widest image and the other images look OK
- 'Fill Height' stretches to the height of the tallest image, other images look OK (this may hide the left/right edges of some images due to page/carousel horizontal spacing)
- 'Fill Entire Slide' stretches all images to fill each carousel slide
- Any other weirdness relating to stretch with overlay, # of items per slide, etc.

**Comment by katknow** [comment]
Overall, I think this is looking much cleaner. The only issue is that when you 'Fill Width' and 'Fill Entire Slide' while using a thumbnail the image gets really grainy if using only one image. However, I'm guessing in those scenarios people would be selecting the 'Full Size' item size anyway as it makes the most sense.
