### ISSUE TITLE
ExhibitBuilder Carousel Block Documentation

### ISSUE THREAD

**Issue by matthewjmckinley** [omeka/plugin-ExhibitBuilder#138]
This new feature is ready for documentation--to be integrated into existing ExhibitBuilder documentation. Here's the testing issue https://github.com/omeka/plugin-ExhibitBuilder/issues/137 for reference, let me know if I can help in any other way.

**Comment by katknow** [comment]
[Here is a draft ](https://github.com/katknow/Drafts/blob/a2329207b27e52cc38ef04a2614ca65909a2cdf4/exhibitbuilder.md)of the ExhibitBuilder documentation with the info on Carousel Block incorporated. Please let me know if I need to change anything. @allanaaa , would you mind taking a look at this as well? I tried to model the additions after the existing layout documentation, but since the layout options for the carousel are significantly different I don't know if I need to be more clear/accessible in my descriptions (particularly with the text box/drop down/checkboxes since all the others just describe drop downs). Once we deem it good to go I'll make a branch on the enduser repo.

**Comment by allanaaa** [comment]
Hi, sorry for the delay on this. This looks pretty good. I wouldn't worry about the "dropdown" etc stuff too much. 

> Layout Options
> Both the File with Text and Gallery blocks include layout options to change the look of the exhibit page. To access these options, click the black triangle button to the right of the Layout Options text at the bottom of the block. This will reveal dropdown menus with options for changing the layout.

Should be "The File with Text, Gallery, and Carousel blocks include...."

Text after the colon, in the Carousel section, should start lowercase, not uppercase. ("Time" and "May")

If there's nothing to say after the colon ("Carousel Title" is self-explanatory I think, unless there's a character limit or something else we can add), then just close it with a period and forget the colon. You could also mention what kind of input each one is, relatively smoothly. That would be more consistent with how we have it on other pages. Up to you. So this part could read:

> The Carousel block has the following options:
>    Carousel title: a text field to enter in your title (maximum X characters).
>    Items per slide (1-10): a dropdown to select the number of items represented on each slide in the carousel.
>    Item file size (thumbnail, square thumbnail, full size).
>    Show item title: a checkbox to include the item title on the slide along with the file.

etc.

If you have a minute, could you also fix the "File Size" bit in the part about the File and File With Text blocks? It has "File Size (full-size, thumbnail, square thumbnail): " and then nothing after the colon.

Last thing: I would love a screenshot of the carousel (and the other blocks too) in action on a public page, just something simple on the Default theme. It seems weird that we have a screenshot of another plugin's effect but none of this plugin's options. Also totally up to you if you want to try to set something up for that.

**Comment by sharonmleon** [comment]
@katknow Checking in on the status of these edits/updates.

**Comment by katknow** [comment]
Changes have been made and are now published to the exhibitbuilder-carousel branch in the documentation--[you can take a look at it here if you'd like](https://github.com/omeka/classic-enduser/blob/e6e172aec297d8b59778b5db91ab0523c11a7150/docs/Plugins/ExhibitBuilder.md). @allanaaa I'm happy to drop in screenshots of the plugin in action, but would you mind pointing to where you'd like them to be within the documentation (my natural inclinations are at places where there are already other screenshots and I'm not sure if you'd want them back to back)? Thanks!
