### ISSUE TITLE
Updated documentation?

### ISSUE THREAD

**Issue by lljohnston** [omeka/plugin-ExhibitBuilder#139]
I can't find updated documentation that explains how to use the Item Group, Exhibit Group, and Collection Group blocks.

**Comment by allanaaa** [comment]
These are not blocks that come with the Omeka exhibit plugin, or with any plugin by the Omeka team.
https://omeka.org/classic/plugins/BlockParty/

You would need to request documentation from here:
https://github.com/jaguillette/BlockParty
