### ISSUE TITLE
In exhibit item show, Item Relations defaults to plugin view, not theme view

### ISSUE THREAD

**Issue by sheepeeh** [omeka/plugin-ExhibitBuilder#71]
I have a custom version of `item-relations-show.php` in `my_theme/common`. When an item page is arrived at through an exhibit, the view is pulled from the ItemRelations plugin instead of from my theme. I got around this by copying the file to `my_theme/exhibit-builder/common`, but I don't think that redundant file should be necessary.

**Comment by zerocrates** [comment]
If you're in a position to test this against the current Omeka core master branch, it should be fixed.

**Comment by sheepeeh** [comment]
Yup, seems to be fixed. Thanks!
