### ISSUE TITLE
Search method to choice an tems never find anything. Even range search with the item_id

### ISSUE THREAD

**Issue by bmenette** [omeka/plugin-ExhibitBuilder#78]

**Comment by zerocrates** [comment]
What versions of Omeka and Exhibit Builder are you using?

**Comment by bmenette** [comment]
Omeka version 2.1.4 
Exhibit Builder version="2.1.2" 

thanks 
----- Mail original -----

**Comment by zerocrates** [comment]
Does the normal advanced search for items work (the one accessible from the Browse Items page)?

**Comment by bmenette** [comment]
Yes, it does. When I've discovered the issue in Exhibit Builder, I've tried the same search with "simple" browse Item search. 

----- Mail original -----

**Comment by bmenette** [comment]
Hello, 

excuse me but my precedent answer weren't strictly exact. I've made three screen shot of three context of advanced search : 
1 Advanced search used in admin interface, with search input and boolean mode among records of any type . 
Results 61, below the 10 first content records. 

2/ Advanced search with formular given by the link at the bottom of search parameters box or content search button in the content browse page. 
No result : 

3/ Public advanced search (site_root/search?query=Gall%C3%A9&query_type=boolean) with formular : 
Results : 46 for the same search 

Thank you if you have any suggestion, 

Sincerily, 

Bruno Ménette 

Membre de / Member EzPAARSE team : 
Accueil AnaLogIST / Project home AnalogIST 
Suivez-nous via / Follow us on Facebook / Twitter / Google+ 

Université de Lorraine - Direction du Numérique / Usage du Numérique 
Présidence site Brabois, INPL , 2, av. de la Forêt de Haye , TSA 30601 
54518 Vandoeuvre FRANCE 

[33] 3.83.59.59.19 

----- Mail original -----

**Comment by zerocrates** [comment]
It doesn't look like you actually attached those screenshots (or Github might not do anything with email attachments).

Number 2 on your list is the "items advanced search," the one that's used by the Exhibit Builder. If that's not working, as it appears is the case, you don't have an Exhibit Builder problem, you have an Omeka core problem. My initial guess is that this is the work of some other plugin that affects that search (and/or the items/browse). Is it *all* searches not working (this is unlikely, as that would usually mean items/browse wouldn't work at all either)?

**Comment by bmenette** [comment]
Thank for the help. 

Yes the number 2 is the "items advanced search," and I thougt like you it's a Omeka core failure. But, then, it means that public advanced search is different than admin advanced search. is that right ? 

Thank you. 

----- Mail original -----

**Comment by bmenette** [comment]
Hello John 

Excuse me, I have forgotten to close thie help task. It has been resolved I don't how, but it works well now. 

Thank 

Bruno 

----- Mail original -----

**Comment by zerocrates** [comment]
That's strange, but good, I suppose.

I'll close the issue for you.
