### ISSUE TITLE
Centering options

### ISSUE THREAD

**Issue by zerocrates** [omeka/plugin-ExhibitBuilder#82]
See http://omeka.org/forums/topic/can-imagesaudio-files-be-centred

I seem to remember there being a way to get things centered by omitting text or some similar method, but it doesn't really look like there's any way to get a centered file from the "file with text" block or a centered showcase from "gallery" blocks.

This seems like a pretty obvious missing option, that we should either have options to achieve in the existing blocks, or have a separate block to accomodate.

@kimisgold do you remember what the situation with centering is?

**Comment by kimisgold** [comment]
I think it's an oversight. We can set `margin: 0 auto` to center blocks pretty easily, but I have some additional use case questions. What does centering mean for 'File With Text', especially with multiple items attached? Is it just item media sitting centered above text? Are the item media centered inline (when possible), or should they clear each other centered on the page?

**Comment by zerocrates** [comment]
My feeling is that when people are talking about centering, they want a single file centered and clearing the full width.
