### ISSUE TITLE
Review cover image form styling

### ISSUE THREAD

**Issue by zerocrates** [omeka/plugin-ExhibitBuilder#84]
@kimisgold, can you take a look at the new "cover image" support? (It's on latest master, and the feature is on the edit page for an exhibit, and it's just for specifically selecting a File that will serve as the thumbnail for the Exhibit)

In particular, I'm interested in whether we should change what the UI looks like on the form. Right now, it's a straight copy of the styling from the attachments on page edit.

My concerns are:
- maybe we should keep the look of that interface different, to avoid any possible confusion with the "real" attachments"
- the colored overlay from the attachment styling obscures what's most important in this context: what the thumbnail will look like
- the "no specific file has been selected" state is sort of confusingly packed into an attachment-like container

**Comment by kimisgold** [comment]
Additional concern: should the ❌do anything? Reset the cover image to the first image in the exhibit?

**Comment by zerocrates** [comment]
It already does that, I think.

**Comment by kimisgold** [comment]
Ah, I see, you have to save the page for that to take effect. It might be because I haven't used ExhibitBuilder in awhile, but the toggle doesn't immediately translate what's going on and makes less sense with only one image being handled. Hmmm.
