### ISSUE TITLE
Test new "cover image" feature

### ISSUE THREAD

**Issue by zerocrates** [omeka/plugin-ExhibitBuilder#85]
The master branch contains a contributed feature that lets users set the "cover image" (generally, the thumbnail) for an exhibit by hand instead of relying on our automatic selection of the first attached file.

We need testing on:

- The upgrade from a previous version of the plugin (this change alters the database). Simply confirming that the plugin operates without errors after upgrade is sufficient testing.
- The UI for selecting the cover image (this is on the edit page for an exhibit), including
  - initial appearance when no cover is selected or the exhibit is new
  - behavior when using "Change" to select a cover image, including the dialog for actually selecting the item and file
  - behavior when removing a selected cover image with the "X" button
  - any concerns about copy or UI generally
- That the selection works as expected: it should apply to both the admin and public sides, both on exhibits browse and when the exhibit is shown with a shortcode or in the Featured Exhibits part of a site homepage.
  - Behavior should be unchanged from previous versions when no cover is selected: the first attached item's thumbnail should be used

**Comment by mebrett** [comment]
Is there a specific branch of Omeka I should be on to test this?

**Comment by zerocrates** [comment]
It shouldn't matter... it should work on 2.3.1 as well as master.

**Comment by mebrett** [comment]
Upgrade went smoothly and everything seems to be working as expected in the list you gave me.

I did notice one hiccup. If you delete the file selected to represent the exhibit, it does not return to the default of showing the first item in the exhibit until you go in and "edit" the exhibit. If you delete the file and then go browse exhibits, it shows up as an exhibit without a cover image.

**Comment by zerocrates** [comment]
I think I'm going to stick with how it works now: avoids possible surprise for people who really wanted to avoid the default thumb.
