### ISSUE TITLE
Test new "file" layout

### ISSUE THREAD

**Issue by zerocrates** [omeka/plugin-ExhibitBuilder#88]
Master of exhibit builder contains a new file-only layout. It's intended to show the file centered and/or at full width.

This issue includes not only basic "does it work" stuff, but also, and more importantly, I'm looking for feedback on whether it works well, whether the name for the block is good, whether it does what's expected.

**Comment by mebrett** [comment]
I think it works well and as expected. "File" seems to be a decent name. Alternatives would be "Standalone file" or "Single file" or "File without Text"

A note for myself for documentation is that, if more than one file is added, they each appear in their own "row" so to speak. And that the caption, like the file, runs the whole width of the page so it's better if you pick the same alignment for both.

**Comment by zerocrates** [comment]
For this one we could remove the caption alignment choice and just force the alignments to change together.

I think part of the problem is that there's not a whole lot of sense to using any of the options but Center. Of course the Exhibit Builder "way" is to be unopinionated on these kinds of things.
